FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    tmux \
    git \
    openssh-client \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:0.9.4 /uv /uvx /bin/